baseURL = "https://teknologi.nl"
languageCode = "en-us"
title = "Teknologi"
copyright = "© 2024, Teknologi. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/AshwinSarimin"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/ashwin-sarimin/"
    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/AshwinSarimin"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]
        [[params.footer.links]]
        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = "https://formspree.io/f/mrgngrow"
