name = "Teknologi"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Teknologi"

homepage = "https://teknologi.nl"
demosite = "https://sec.gd/hugo/themes/arcana/"

tags = ["blog","business","html5up","responsive"]
features = ["blog"]

[author]
  name = "Ashwin Sarimin"
  homepage = "https://teknologi.nl"

[original]
  name = "@ajlkn"
  homepage = "https://html5up.net/"
